name: printing_example
description: Pdf Printing Example

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  printing:
  path_provider:
  flutter_full_pdf_viewer:
  cupertino_icons:
  qr:
  markdown:

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  printing:
    path: ..
  pdf:
    path: ../../pdf

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: arabic
      fonts:
        - asset: assets/hacen-tunisia.ttf
